export enum WorkflowHttpAction {
  SUBMIT = 'SUBMIT',
  START_REVIEW = 'START_REVIEW',
  CONTINUE_REVIEW = 'CONTINUE_REVIEW',
  REQUEST_INFO = 'REQUEST_INFO',
  COMPLETE_REVIEW = 'COMPLETE_REVIEW',
  RESUBMIT = 'RESUBMIT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
}
