export enum DocumentType {
  CERTIFICATE_OF_INCORPORATION = 'CERTIFICATE_OF_INCORPORATION',
  ARTICLES_OF_ASSOCIATION = 'ARTICLES_OF_ASSOCIATION',
  AUDITED_FINANCIAL_STATEMENTS = 'AUDITED_FINANCIAL_STATEMENTS',
  BUSINESS_PLAN = 'BUSINESS_PLAN',
  TAX_CLEARANCE = 'TAX_CLEARANCE',
  DIRECTOR_IDENTIFICATION = 'DIRECTOR_IDENTIFICATION',
  OTHER = 'OTHER',
}
